//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestionTest2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class EmpresaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmpresaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string razonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string webField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmpresaID {
            get {
                return this.EmpresaIDField;
            }
            set {
                if ((this.EmpresaIDField.Equals(value) != true)) {
                    this.EmpresaIDField = value;
                    this.RaisePropertyChanged("EmpresaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cif {
            get {
                return this.cifField;
            }
            set {
                if ((object.ReferenceEquals(this.cifField, value) != true)) {
                    this.cifField = value;
                    this.RaisePropertyChanged("cif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreComercialField, value) != true)) {
                    this.nombreComercialField = value;
                    this.RaisePropertyChanged("nombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.razonSocialField, value) != true)) {
                    this.razonSocialField = value;
                    this.RaisePropertyChanged("razonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sector {
            get {
                return this.sectorField;
            }
            set {
                if ((object.ReferenceEquals(this.sectorField, value) != true)) {
                    this.sectorField = value;
                    this.RaisePropertyChanged("sector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string web {
            get {
                return this.webField;
            }
            set {
                if ((object.ReferenceEquals(this.webField, value) != true)) {
                    this.webField = value;
                    this.RaisePropertyChanged("web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactoData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class ContactoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idContacto {
            get {
                return this.idContactoField;
            }
            set {
                if ((this.idContactoField.Equals(value) != true)) {
                    this.idContactoField = value;
                    this.RaisePropertyChanged("idContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nif {
            get {
                return this.nifField;
            }
            set {
                if ((object.ReferenceEquals(this.nifField, value) != true)) {
                    this.nifField = value;
                    this.RaisePropertyChanged("nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class EmailData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailID {
            get {
                return this.EmailIDField;
            }
            set {
                if ((this.EmailIDField.Equals(value) != true)) {
                    this.EmailIDField = value;
                    this.RaisePropertyChanged("EmailID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class DireccionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string domicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string poblacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.codPostalField, value) != true)) {
                    this.codPostalField = value;
                    this.RaisePropertyChanged("codPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string domicilio {
            get {
                return this.domicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.domicilioField, value) != true)) {
                    this.domicilioField = value;
                    this.RaisePropertyChanged("domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                if ((this.idDireccionField.Equals(value) != true)) {
                    this.idDireccionField = value;
                    this.RaisePropertyChanged("idDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string poblacion {
            get {
                return this.poblacionField;
            }
            set {
                if ((object.ReferenceEquals(this.poblacionField, value) != true)) {
                    this.poblacionField = value;
                    this.RaisePropertyChanged("poblacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SectorData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class SectorData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSectorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSector {
            get {
                return this.idSectorField;
            }
            set {
                if ((this.idSectorField.Equals(value) != true)) {
                    this.idSectorField = value;
                    this.RaisePropertyChanged("idSector");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoAccion", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class EstadoAccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstadoAccion {
            get {
                return this.idEstadoAccionField;
            }
            set {
                if ((this.idEstadoAccionField.Equals(value) != true)) {
                    this.idEstadoAccionField = value;
                    this.RaisePropertyChanged("idEstadoAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonoData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class TelefonoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTelefono {
            get {
                return this.idTelefonoField;
            }
            set {
                if ((this.idTelefonoField.Equals(value) != true)) {
                    this.idTelefonoField = value;
                    this.RaisePropertyChanged("idTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroField, value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDeAccionData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class TipoDeAccionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoAccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoAccion {
            get {
                return this.idTipoAccionField;
            }
            set {
                if ((this.idTipoAccionField.Equals(value) != true)) {
                    this.idTipoAccionField = value;
                    this.RaisePropertyChanged("idTipoAccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class UsuarioData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionComercialData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class AccionComercialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.comentariosField, value) != true)) {
                    this.comentariosField = value;
                    this.RaisePropertyChanged("comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                if ((this.fechaHoraField.Equals(value) != true)) {
                    this.fechaHoraField = value;
                    this.RaisePropertyChanged("fechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                if ((this.idAccionField.Equals(value) != true)) {
                    this.idAccionField = value;
                    this.RaisePropertyChanged("idAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                if ((this.idEmpresaField.Equals(value) != true)) {
                    this.idEmpresaField = value;
                    this.RaisePropertyChanged("idEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstadoAccion {
            get {
                return this.idEstadoAccionField;
            }
            set {
                if ((this.idEstadoAccionField.Equals(value) != true)) {
                    this.idEstadoAccionField = value;
                    this.RaisePropertyChanged("idEstadoAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoAccion {
            get {
                return this.idTipoAccionField;
            }
            set {
                if ((this.idTipoAccionField.Equals(value) != true)) {
                    this.idTipoAccionField = value;
                    this.RaisePropertyChanged("idTipoAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionComercialMostrarData", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestion")]
    [System.SerializableAttribute()]
    public partial class AccionComercialMostrarData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionEstadoAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionTipoAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.comentariosField, value) != true)) {
                    this.comentariosField = value;
                    this.RaisePropertyChanged("comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionEstadoAccion {
            get {
                return this.descripcionEstadoAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionEstadoAccionField, value) != true)) {
                    this.descripcionEstadoAccionField = value;
                    this.RaisePropertyChanged("descripcionEstadoAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcionTipoAccion {
            get {
                return this.descripcionTipoAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionTipoAccionField, value) != true)) {
                    this.descripcionTipoAccionField = value;
                    this.RaisePropertyChanged("descripcionTipoAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                if ((this.fechaHoraField.Equals(value) != true)) {
                    this.fechaHoraField = value;
                    this.RaisePropertyChanged("fechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                if ((this.idAccionField.Equals(value) != true)) {
                    this.idAccionField = value;
                    this.RaisePropertyChanged("idAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreEmpresaField, value) != true)) {
                    this.nombreEmpresaField = value;
                    this.RaisePropertyChanged("nombreEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioGestion")]
    public interface IServicioGestion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmail", ReplyAction="http://tempuri.org/IServicioGestion/addEmailResponse")]
        bool addEmail(string correo, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmail", ReplyAction="http://tempuri.org/IServicioGestion/addEmailResponse")]
        System.Threading.Tasks.Task<bool> addEmailAsync(string correo, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmail", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmailResponse")]
        ServicioGestionTest2.ServiceReference1.EmailData[] getAllEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmail", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmailResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getAllEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailId", ReplyAction="http://tempuri.org/IServicioGestion/getEmailIdResponse")]
        ServicioGestionTest2.ServiceReference1.EmailData getEmailId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailId", ReplyAction="http://tempuri.org/IServicioGestion/getEmailIdResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData> getEmailIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailCorreo", ReplyAction="http://tempuri.org/IServicioGestion/getEmailCorreoResponse")]
        ServicioGestionTest2.ServiceReference1.EmailData getEmailCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailCorreo", ReplyAction="http://tempuri.org/IServicioGestion/getEmailCorreoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData> getEmailCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmail", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmailResponse")]
        bool deleteEmail(int idEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmail", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmailResponse")]
        System.Threading.Tasks.Task<bool> deleteEmailAsync(int idEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmail", ReplyAction="http://tempuri.org/IServicioGestion/editEmailResponse")]
        bool editEmail(int idEmail, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmail", ReplyAction="http://tempuri.org/IServicioGestion/editEmailResponse")]
        System.Threading.Tasks.Task<bool> editEmailAsync(int idEmail, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/addEmpresaResponse")]
        bool addEmpresa(string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/addEmpresaResponse")]
        System.Threading.Tasks.Task<bool> addEmpresaAsync(string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.EmpresaData[] getAllEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData[]> getAllEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaCif", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaCifResponse")]
        ServicioGestionTest2.ServiceReference1.EmpresaData getEmpresaCif(string cif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaCif", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaCifResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData> getEmpresaCifAsync(string cif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaId", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaIdResponse")]
        ServicioGestionTest2.ServiceReference1.EmpresaData getEmpresaId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaId", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaIdResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData> getEmpresaIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaSector", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaSectorResponse")]
        ServicioGestionTest2.ServiceReference1.EmpresaData[] getEmpresaSector(int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaSector", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaSectorResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData[]> getEmpresaSectorAsync(int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmpresaResponse")]
        bool deleteEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmpresaResponse")]
        System.Threading.Tasks.Task<bool> deleteEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/editEmpresaResponse")]
        bool editEmpresa(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/editEmpresaResponse")]
        System.Threading.Tasks.Task<bool> editEmpresaAsync(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getMailEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.EmailData[] getMailEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getMailEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getMailEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailContacto", ReplyAction="http://tempuri.org/IServicioGestion/getMailContactoResponse")]
        ServicioGestionTest2.ServiceReference1.EmailData[] getMailContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailContacto", ReplyAction="http://tempuri.org/IServicioGestion/getMailContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getMailContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddDireccion", ReplyAction="http://tempuri.org/IServicioGestion/AddDireccionResponse")]
        bool AddDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddDireccion", ReplyAction="http://tempuri.org/IServicioGestion/AddDireccionResponse")]
        System.Threading.Tasks.Task<bool> AddDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteDireccion", ReplyAction="http://tempuri.org/IServicioGestion/DeleteDireccionResponse")]
        bool DeleteDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteDireccion", ReplyAction="http://tempuri.org/IServicioGestion/DeleteDireccionResponse")]
        System.Threading.Tasks.Task<bool> DeleteDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditDireccion", ReplyAction="http://tempuri.org/IServicioGestion/EditDireccionResponse")]
        bool EditDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditDireccion", ReplyAction="http://tempuri.org/IServicioGestion/EditDireccionResponse")]
        System.Threading.Tasks.Task<bool> EditDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetDireccion", ReplyAction="http://tempuri.org/IServicioGestion/GetDireccionResponse")]
        ServicioGestionTest2.ServiceReference1.DireccionData[] GetDireccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetDireccion", ReplyAction="http://tempuri.org/IServicioGestion/GetDireccionResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> GetDireccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetSector", ReplyAction="http://tempuri.org/IServicioGestion/GetSectorResponse")]
        ServicioGestionTest2.ServiceReference1.SectorData[] GetSector();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetSector", ReplyAction="http://tempuri.org/IServicioGestion/GetSectorResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.SectorData[]> GetSectorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetEstadoAccionResponse")]
        ServicioGestionTest2.ServiceReference1.EstadoAccion[] GetEstadoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetEstadoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EstadoAccion[]> GetEstadoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllEstadoAccionResponse")]
        ServicioGestionTest2.ServiceReference1.EstadoAccion[] GetAllEstadoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllEstadoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EstadoAccion[]> GetAllEstadoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetContactoResponse")]
        ServicioGestionTest2.ServiceReference1.ContactoData[] GetContacto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.ContactoData[]> GetContactoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteContacto", ReplyAction="http://tempuri.org/IServicioGestion/DeleteContactoResponse")]
        bool DeleteContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteContacto", ReplyAction="http://tempuri.org/IServicioGestion/DeleteContactoResponse")]
        System.Threading.Tasks.Task<bool> DeleteContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddContacto", ReplyAction="http://tempuri.org/IServicioGestion/AddContactoResponse")]
        bool AddContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddContacto", ReplyAction="http://tempuri.org/IServicioGestion/AddContactoResponse")]
        System.Threading.Tasks.Task<bool> AddContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditContacto", ReplyAction="http://tempuri.org/IServicioGestion/EditContactoResponse")]
        bool EditContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditContacto", ReplyAction="http://tempuri.org/IServicioGestion/EditContactoResponse")]
        System.Threading.Tasks.Task<bool> EditContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.DireccionData[] getDirecionesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> getDirecionesEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesContacto", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesContactoResponse")]
        ServicioGestionTest2.ServiceReference1.DireccionData[] getDirecionesContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesContacto", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> getDirecionesContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetNumeroTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetNumeroTelefonoResponse")]
        ServicioGestionTest2.ServiceReference1.TelefonoData GetNumeroTelefono(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetNumeroTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetNumeroTelefonoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData> GetNumeroTelefonoAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTelefonoResponse")]
        ServicioGestionTest2.ServiceReference1.TelefonoData GetIdTelefono(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTelefonoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData> GetIdTelefonoAsync(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTelefonos", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTelefonosResponse")]
        ServicioGestionTest2.ServiceReference1.TelefonoData[] GetAllTelefonos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTelefonos", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTelefonosResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetAllTelefonosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddTelefono", ReplyAction="http://tempuri.org/IServicioGestion/AddTelefonoResponse")]
        bool AddTelefono(ServicioGestionTest2.ServiceReference1.TelefonoData t, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddTelefono", ReplyAction="http://tempuri.org/IServicioGestion/AddTelefonoResponse")]
        System.Threading.Tasks.Task<bool> AddTelefonoAsync(ServicioGestionTest2.ServiceReference1.TelefonoData t, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditTelefono", ReplyAction="http://tempuri.org/IServicioGestion/EditTelefonoResponse")]
        bool EditTelefono(ServicioGestionTest2.ServiceReference1.TelefonoData t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditTelefono", ReplyAction="http://tempuri.org/IServicioGestion/EditTelefonoResponse")]
        System.Threading.Tasks.Task<bool> EditTelefonoAsync(ServicioGestionTest2.ServiceReference1.TelefonoData t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteTelefono", ReplyAction="http://tempuri.org/IServicioGestion/DeleteTelefonoResponse")]
        bool DeleteTelefono(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteTelefono", ReplyAction="http://tempuri.org/IServicioGestion/DeleteTelefonoResponse")]
        System.Threading.Tasks.Task<bool> DeleteTelefonoAsync(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTipoAccionResponse")]
        ServicioGestionTest2.ServiceReference1.TipoDeAccionData GetIdTipoAccion(int idTipoAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTipoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TipoDeAccionData> GetIdTipoAccionAsync(int idTipoAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTipoAccionResponse")]
        ServicioGestionTest2.ServiceReference1.TipoDeAccionData[] GetAllTipoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTipoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TipoDeAccionData[]> GetAllTipoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.TelefonoData[] GetTelefonosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetTelefonosEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContactosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetContactosEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.ContactoData[] GetContactosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContactosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetContactosEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.ContactoData[]> GetContactosEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosContactoResponse")]
        ServicioGestionTest2.ServiceReference1.TelefonoData[] GetTelefonosContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetTelefonosContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addUsuario", ReplyAction="http://tempuri.org/IServicioGestion/addUsuarioResponse")]
        bool addUsuario(ServicioGestionTest2.ServiceReference1.UsuarioData usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addUsuario", ReplyAction="http://tempuri.org/IServicioGestion/addUsuarioResponse")]
        System.Threading.Tasks.Task<bool> addUsuarioAsync(ServicioGestionTest2.ServiceReference1.UsuarioData usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteUsuario", ReplyAction="http://tempuri.org/IServicioGestion/deleteUsuarioResponse")]
        bool deleteUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteUsuario", ReplyAction="http://tempuri.org/IServicioGestion/deleteUsuarioResponse")]
        System.Threading.Tasks.Task<bool> deleteUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editUsuario", ReplyAction="http://tempuri.org/IServicioGestion/editUsuarioResponse")]
        bool editUsuario(int idUsuario, ServicioGestionTest2.ServiceReference1.UsuarioData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editUsuario", ReplyAction="http://tempuri.org/IServicioGestion/editUsuarioResponse")]
        System.Threading.Tasks.Task<bool> editUsuarioAsync(int idUsuario, ServicioGestionTest2.ServiceReference1.UsuarioData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAllUsuariosResponse")]
        ServicioGestionTest2.ServiceReference1.UsuarioData[] getAllUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAllUsuariosResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.UsuarioData[]> getAllUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getUsuario", ReplyAction="http://tempuri.org/IServicioGestion/getUsuarioResponse")]
        ServicioGestionTest2.ServiceReference1.UsuarioData getUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getUsuario", ReplyAction="http://tempuri.org/IServicioGestion/getUsuarioResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.UsuarioData> getUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/addAccionComercialResponse")]
        bool addAccionComercial(ServicioGestionTest2.ServiceReference1.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/addAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> addAccionComercialAsync(ServicioGestionTest2.ServiceReference1.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/deleteAccionComercialResponse")]
        bool deleteAccionComercial(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/deleteAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> deleteAccionComercialAsync(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/editAccionComercialResponse")]
        bool editAccionComercial(int idAccion, ServicioGestionTest2.ServiceReference1.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/editAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> editAccionComercialAsync(int idAccion, ServicioGestionTest2.ServiceReference1.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllAccionesComerciales", ReplyAction="http://tempuri.org/IServicioGestion/getAllAccionesComercialesResponse")]
        ServicioGestionTest2.ServiceReference1.AccionComercialMostrarData[] getAllAccionesComerciales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllAccionesComerciales", ReplyAction="http://tempuri.org/IServicioGestion/getAllAccionesComercialesResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialMostrarData[]> getAllAccionesComercialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/getAccionComercialResponse")]
        ServicioGestionTest2.ServiceReference1.AccionComercialData getAccionComercial(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/getAccionComercialResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData> getAccionComercialAsync(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuariosResponse")]
        ServicioGestionTest2.ServiceReference1.AccionComercialData[] getAccionesComercialesUsuarios(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuariosResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData[]> getAccionesComercialesUsuariosAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresaResponse")]
        ServicioGestionTest2.ServiceReference1.AccionComercialData[] getAccionesComercialesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData[]> getAccionesComercialesEmpresaAsync(int idEmpresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGestionChannel : ServicioGestionTest2.ServiceReference1.IServicioGestion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGestionClient : System.ServiceModel.ClientBase<ServicioGestionTest2.ServiceReference1.IServicioGestion>, ServicioGestionTest2.ServiceReference1.IServicioGestion {
        
        public ServicioGestionClient() {
        }
        
        public ServicioGestionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGestionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addEmail(string correo, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.addEmail(correo, empData, conData);
        }
        
        public System.Threading.Tasks.Task<bool> addEmailAsync(string correo, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.addEmailAsync(correo, empData, conData);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmailData[] getAllEmail() {
            return base.Channel.getAllEmail();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getAllEmailAsync() {
            return base.Channel.getAllEmailAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.EmailData getEmailId(int id) {
            return base.Channel.getEmailId(id);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData> getEmailIdAsync(int id) {
            return base.Channel.getEmailIdAsync(id);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmailData getEmailCorreo(string correo) {
            return base.Channel.getEmailCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData> getEmailCorreoAsync(string correo) {
            return base.Channel.getEmailCorreoAsync(correo);
        }
        
        public bool deleteEmail(int idEmail) {
            return base.Channel.deleteEmail(idEmail);
        }
        
        public System.Threading.Tasks.Task<bool> deleteEmailAsync(int idEmail) {
            return base.Channel.deleteEmailAsync(idEmail);
        }
        
        public bool editEmail(int idEmail, string correo) {
            return base.Channel.editEmail(idEmail, correo);
        }
        
        public System.Threading.Tasks.Task<bool> editEmailAsync(int idEmail, string correo) {
            return base.Channel.editEmailAsync(idEmail, correo);
        }
        
        public bool addEmpresa(string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.addEmpresa(cif, nombreComercial, razon, web, sector);
        }
        
        public System.Threading.Tasks.Task<bool> addEmpresaAsync(string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.addEmpresaAsync(cif, nombreComercial, razon, web, sector);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmpresaData[] getAllEmpresa() {
            return base.Channel.getAllEmpresa();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData[]> getAllEmpresaAsync() {
            return base.Channel.getAllEmpresaAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.EmpresaData getEmpresaCif(string cif) {
            return base.Channel.getEmpresaCif(cif);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData> getEmpresaCifAsync(string cif) {
            return base.Channel.getEmpresaCifAsync(cif);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmpresaData getEmpresaId(int id) {
            return base.Channel.getEmpresaId(id);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData> getEmpresaIdAsync(int id) {
            return base.Channel.getEmpresaIdAsync(id);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmpresaData[] getEmpresaSector(int idSector) {
            return base.Channel.getEmpresaSector(idSector);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmpresaData[]> getEmpresaSectorAsync(int idSector) {
            return base.Channel.getEmpresaSectorAsync(idSector);
        }
        
        public bool deleteEmpresa(int idEmpresa) {
            return base.Channel.deleteEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<bool> deleteEmpresaAsync(int idEmpresa) {
            return base.Channel.deleteEmpresaAsync(idEmpresa);
        }
        
        public bool editEmpresa(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.editEmpresa(idEmpresa, cif, nombreComercial, razon, web, sector);
        }
        
        public System.Threading.Tasks.Task<bool> editEmpresaAsync(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.editEmpresaAsync(idEmpresa, cif, nombreComercial, razon, web, sector);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmailData[] getMailEmpresa(int idEmpresa) {
            return base.Channel.getMailEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getMailEmpresaAsync(int idEmpresa) {
            return base.Channel.getMailEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestionTest2.ServiceReference1.EmailData[] getMailContacto(int idContacto) {
            return base.Channel.getMailContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EmailData[]> getMailContactoAsync(int idContacto) {
            return base.Channel.getMailContactoAsync(idContacto);
        }
        
        public bool AddDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.AddDireccion(street, empData, conData);
        }
        
        public System.Threading.Tasks.Task<bool> AddDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.AddDireccionAsync(street, empData, conData);
        }
        
        public bool DeleteDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, int id) {
            return base.Channel.DeleteDireccion(street, id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, int id) {
            return base.Channel.DeleteDireccionAsync(street, id);
        }
        
        public bool EditDireccion(ServicioGestionTest2.ServiceReference1.DireccionData street, int id) {
            return base.Channel.EditDireccion(street, id);
        }
        
        public System.Threading.Tasks.Task<bool> EditDireccionAsync(ServicioGestionTest2.ServiceReference1.DireccionData street, int id) {
            return base.Channel.EditDireccionAsync(street, id);
        }
        
        public ServicioGestionTest2.ServiceReference1.DireccionData[] GetDireccion() {
            return base.Channel.GetDireccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> GetDireccionAsync() {
            return base.Channel.GetDireccionAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.SectorData[] GetSector() {
            return base.Channel.GetSector();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.SectorData[]> GetSectorAsync() {
            return base.Channel.GetSectorAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.EstadoAccion[] GetEstadoAccion() {
            return base.Channel.GetEstadoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EstadoAccion[]> GetEstadoAccionAsync() {
            return base.Channel.GetEstadoAccionAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.EstadoAccion[] GetAllEstadoAccion() {
            return base.Channel.GetAllEstadoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.EstadoAccion[]> GetAllEstadoAccionAsync() {
            return base.Channel.GetAllEstadoAccionAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.ContactoData[] GetContacto() {
            return base.Channel.GetContacto();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.ContactoData[]> GetContactoAsync() {
            return base.Channel.GetContactoAsync();
        }
        
        public bool DeleteContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id) {
            return base.Channel.DeleteContacto(contacto, id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id) {
            return base.Channel.DeleteContactoAsync(contacto, id);
        }
        
        public bool AddContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto) {
            return base.Channel.AddContacto(contacto);
        }
        
        public System.Threading.Tasks.Task<bool> AddContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto) {
            return base.Channel.AddContactoAsync(contacto);
        }
        
        public bool EditContacto(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id) {
            return base.Channel.EditContacto(contacto, id);
        }
        
        public System.Threading.Tasks.Task<bool> EditContactoAsync(ServicioGestionTest2.ServiceReference1.ContactoData contacto, int id) {
            return base.Channel.EditContactoAsync(contacto, id);
        }
        
        public ServicioGestionTest2.ServiceReference1.DireccionData[] getDirecionesEmpresa(int idEmpresa) {
            return base.Channel.getDirecionesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> getDirecionesEmpresaAsync(int idEmpresa) {
            return base.Channel.getDirecionesEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestionTest2.ServiceReference1.DireccionData[] getDirecionesContacto(int idContacto) {
            return base.Channel.getDirecionesContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.DireccionData[]> getDirecionesContactoAsync(int idContacto) {
            return base.Channel.getDirecionesContactoAsync(idContacto);
        }
        
        public ServicioGestionTest2.ServiceReference1.TelefonoData GetNumeroTelefono(string telefono) {
            return base.Channel.GetNumeroTelefono(telefono);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData> GetNumeroTelefonoAsync(string telefono) {
            return base.Channel.GetNumeroTelefonoAsync(telefono);
        }
        
        public ServicioGestionTest2.ServiceReference1.TelefonoData GetIdTelefono(int idTelefono) {
            return base.Channel.GetIdTelefono(idTelefono);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData> GetIdTelefonoAsync(int idTelefono) {
            return base.Channel.GetIdTelefonoAsync(idTelefono);
        }
        
        public ServicioGestionTest2.ServiceReference1.TelefonoData[] GetAllTelefonos() {
            return base.Channel.GetAllTelefonos();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetAllTelefonosAsync() {
            return base.Channel.GetAllTelefonosAsync();
        }
        
        public bool AddTelefono(ServicioGestionTest2.ServiceReference1.TelefonoData t, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.AddTelefono(t, empData, conData);
        }
        
        public System.Threading.Tasks.Task<bool> AddTelefonoAsync(ServicioGestionTest2.ServiceReference1.TelefonoData t, ServicioGestionTest2.ServiceReference1.EmpresaData empData, ServicioGestionTest2.ServiceReference1.ContactoData conData) {
            return base.Channel.AddTelefonoAsync(t, empData, conData);
        }
        
        public bool EditTelefono(ServicioGestionTest2.ServiceReference1.TelefonoData t) {
            return base.Channel.EditTelefono(t);
        }
        
        public System.Threading.Tasks.Task<bool> EditTelefonoAsync(ServicioGestionTest2.ServiceReference1.TelefonoData t) {
            return base.Channel.EditTelefonoAsync(t);
        }
        
        public bool DeleteTelefono(int idTelefono) {
            return base.Channel.DeleteTelefono(idTelefono);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTelefonoAsync(int idTelefono) {
            return base.Channel.DeleteTelefonoAsync(idTelefono);
        }
        
        public ServicioGestionTest2.ServiceReference1.TipoDeAccionData GetIdTipoAccion(int idTipoAccion) {
            return base.Channel.GetIdTipoAccion(idTipoAccion);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TipoDeAccionData> GetIdTipoAccionAsync(int idTipoAccion) {
            return base.Channel.GetIdTipoAccionAsync(idTipoAccion);
        }
        
        public ServicioGestionTest2.ServiceReference1.TipoDeAccionData[] GetAllTipoAccion() {
            return base.Channel.GetAllTipoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TipoDeAccionData[]> GetAllTipoAccionAsync() {
            return base.Channel.GetAllTipoAccionAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.TelefonoData[] GetTelefonosEmpresa(int idEmpresa) {
            return base.Channel.GetTelefonosEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetTelefonosEmpresaAsync(int idEmpresa) {
            return base.Channel.GetTelefonosEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestionTest2.ServiceReference1.ContactoData[] GetContactosEmpresa(int idEmpresa) {
            return base.Channel.GetContactosEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.ContactoData[]> GetContactosEmpresaAsync(int idEmpresa) {
            return base.Channel.GetContactosEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestionTest2.ServiceReference1.TelefonoData[] GetTelefonosContacto(int idContacto) {
            return base.Channel.GetTelefonosContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.TelefonoData[]> GetTelefonosContactoAsync(int idContacto) {
            return base.Channel.GetTelefonosContactoAsync(idContacto);
        }
        
        public bool addUsuario(ServicioGestionTest2.ServiceReference1.UsuarioData usuario) {
            return base.Channel.addUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> addUsuarioAsync(ServicioGestionTest2.ServiceReference1.UsuarioData usuario) {
            return base.Channel.addUsuarioAsync(usuario);
        }
        
        public bool deleteUsuario(int idUsuario) {
            return base.Channel.deleteUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> deleteUsuarioAsync(int idUsuario) {
            return base.Channel.deleteUsuarioAsync(idUsuario);
        }
        
        public bool editUsuario(int idUsuario, ServicioGestionTest2.ServiceReference1.UsuarioData user) {
            return base.Channel.editUsuario(idUsuario, user);
        }
        
        public System.Threading.Tasks.Task<bool> editUsuarioAsync(int idUsuario, ServicioGestionTest2.ServiceReference1.UsuarioData user) {
            return base.Channel.editUsuarioAsync(idUsuario, user);
        }
        
        public ServicioGestionTest2.ServiceReference1.UsuarioData[] getAllUsuarios() {
            return base.Channel.getAllUsuarios();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.UsuarioData[]> getAllUsuariosAsync() {
            return base.Channel.getAllUsuariosAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.UsuarioData getUsuario(int idUsuario) {
            return base.Channel.getUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.UsuarioData> getUsuarioAsync(int idUsuario) {
            return base.Channel.getUsuarioAsync(idUsuario);
        }
        
        public bool addAccionComercial(ServicioGestionTest2.ServiceReference1.AccionComercialData accion) {
            return base.Channel.addAccionComercial(accion);
        }
        
        public System.Threading.Tasks.Task<bool> addAccionComercialAsync(ServicioGestionTest2.ServiceReference1.AccionComercialData accion) {
            return base.Channel.addAccionComercialAsync(accion);
        }
        
        public bool deleteAccionComercial(int idAccion) {
            return base.Channel.deleteAccionComercial(idAccion);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAccionComercialAsync(int idAccion) {
            return base.Channel.deleteAccionComercialAsync(idAccion);
        }
        
        public bool editAccionComercial(int idAccion, ServicioGestionTest2.ServiceReference1.AccionComercialData accion) {
            return base.Channel.editAccionComercial(idAccion, accion);
        }
        
        public System.Threading.Tasks.Task<bool> editAccionComercialAsync(int idAccion, ServicioGestionTest2.ServiceReference1.AccionComercialData accion) {
            return base.Channel.editAccionComercialAsync(idAccion, accion);
        }
        
        public ServicioGestionTest2.ServiceReference1.AccionComercialMostrarData[] getAllAccionesComerciales() {
            return base.Channel.getAllAccionesComerciales();
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialMostrarData[]> getAllAccionesComercialesAsync() {
            return base.Channel.getAllAccionesComercialesAsync();
        }
        
        public ServicioGestionTest2.ServiceReference1.AccionComercialData getAccionComercial(int idAccion) {
            return base.Channel.getAccionComercial(idAccion);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData> getAccionComercialAsync(int idAccion) {
            return base.Channel.getAccionComercialAsync(idAccion);
        }
        
        public ServicioGestionTest2.ServiceReference1.AccionComercialData[] getAccionesComercialesUsuarios(int idUsuario) {
            return base.Channel.getAccionesComercialesUsuarios(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData[]> getAccionesComercialesUsuariosAsync(int idUsuario) {
            return base.Channel.getAccionesComercialesUsuariosAsync(idUsuario);
        }
        
        public ServicioGestionTest2.ServiceReference1.AccionComercialData[] getAccionesComercialesEmpresa(int idEmpresa) {
            return base.Channel.getAccionesComercialesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestionTest2.ServiceReference1.AccionComercialData[]> getAccionesComercialesEmpresaAsync(int idEmpresa) {
            return base.Channel.getAccionesComercialesEmpresaAsync(idEmpresa);
        }
    }
}
