//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionComercial
    {
        public int idAccion { get; set; }
        public string descripcion { get; set; }
        public string comentarios { get; set; }
        public System.DateTime fechaHora { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTipoAccion { get; set; }
        public Nullable<int> idEstadoAccion { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EstadoDeAccion EstadoDeAccion { get; set; }
        public virtual TipoDeAccion TipoDeAccion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
