//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public Contacto()
        {
            this.Direccion = new HashSet<Direccion>();
            this.Email = new HashSet<Email>();
            this.Telefono = new HashSet<Telefono>();
        }
    
        public int idContacto { get; set; }
        public string nif { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Telefono> Telefono { get; set; }
    }
}
