//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public Email()
        {
            this.Contacto = new HashSet<Contacto>();
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int idEmail { get; set; }
        public string correo { get; set; }
    
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
