//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.AccionComercial = new HashSet<AccionComercial>();
            this.Contacto = new HashSet<Contacto>();
            this.Direccion = new HashSet<Direccion>();
            this.Email = new HashSet<Email>();
            this.Telefono = new HashSet<Telefono>();
        }
    
        public int idEmpresa { get; set; }
        public string cif { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public string web { get; set; }
        public Nullable<int> idSector { get; set; }
    
        public virtual ICollection<AccionComercial> AccionComercial { get; set; }
        public virtual ICollection<Contacto> Contacto { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual ICollection<Direccion> Direccion { get; set; }
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Telefono> Telefono { get; set; }
    }
}
