//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestion.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int idSector { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
