//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioGestionTestSpace.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicioGestion")]
    public interface IServicioGestion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmail", ReplyAction="http://tempuri.org/IServicioGestion/addEmailResponse")]
        int addEmail(string correo, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmail", ReplyAction="http://tempuri.org/IServicioGestion/addEmailResponse")]
        System.Threading.Tasks.Task<int> addEmailAsync(string correo, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmail", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmailResponse")]
        ServicioGestion.EmailData[] getAllEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmail", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmailResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getAllEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailId", ReplyAction="http://tempuri.org/IServicioGestion/getEmailIdResponse")]
        ServicioGestion.EmailData getEmailId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailId", ReplyAction="http://tempuri.org/IServicioGestion/getEmailIdResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmailData> getEmailIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailCorreo", ReplyAction="http://tempuri.org/IServicioGestion/getEmailCorreoResponse")]
        ServicioGestion.EmailData getEmailCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmailCorreo", ReplyAction="http://tempuri.org/IServicioGestion/getEmailCorreoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmailData> getEmailCorreoAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmail", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmailResponse")]
        bool deleteEmail(int idEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmail", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmailResponse")]
        System.Threading.Tasks.Task<bool> deleteEmailAsync(int idEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmail", ReplyAction="http://tempuri.org/IServicioGestion/editEmailResponse")]
        bool editEmail(int idEmail, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmail", ReplyAction="http://tempuri.org/IServicioGestion/editEmailResponse")]
        System.Threading.Tasks.Task<bool> editEmailAsync(int idEmail, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/addEmpresaResponse")]
        bool addEmpresa(string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/addEmpresaResponse")]
        System.Threading.Tasks.Task<bool> addEmpresaAsync(string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmpresaResponse")]
        ServicioGestion.EmpresaData[] getAllEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAllEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmpresaData[]> getAllEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaCif", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaCifResponse")]
        ServicioGestion.EmpresaData getEmpresaCif(string cif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaCif", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaCifResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmpresaData> getEmpresaCifAsync(string cif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaId", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaIdResponse")]
        ServicioGestion.EmpresaData getEmpresaId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaId", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaIdResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmpresaData> getEmpresaIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaSector", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaSectorResponse")]
        ServicioGestion.EmpresaData[] getEmpresaSector(int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getEmpresaSector", ReplyAction="http://tempuri.org/IServicioGestion/getEmpresaSectorResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmpresaData[]> getEmpresaSectorAsync(int idSector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmpresaResponse")]
        bool deleteEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/deleteEmpresaResponse")]
        System.Threading.Tasks.Task<bool> deleteEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/editEmpresaResponse")]
        bool editEmpresa(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/editEmpresaResponse")]
        System.Threading.Tasks.Task<bool> editEmpresaAsync(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getMailEmpresaResponse")]
        ServicioGestion.EmailData[] getMailEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getMailEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getMailEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailContacto", ReplyAction="http://tempuri.org/IServicioGestion/getMailContactoResponse")]
        ServicioGestion.EmailData[] getMailContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getMailContacto", ReplyAction="http://tempuri.org/IServicioGestion/getMailContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getMailContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddDireccion", ReplyAction="http://tempuri.org/IServicioGestion/AddDireccionResponse")]
        bool AddDireccion(ServicioGestion.DireccionData street, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddDireccion", ReplyAction="http://tempuri.org/IServicioGestion/AddDireccionResponse")]
        System.Threading.Tasks.Task<bool> AddDireccionAsync(ServicioGestion.DireccionData street, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteDireccion", ReplyAction="http://tempuri.org/IServicioGestion/DeleteDireccionResponse")]
        bool DeleteDireccion(ServicioGestion.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteDireccion", ReplyAction="http://tempuri.org/IServicioGestion/DeleteDireccionResponse")]
        System.Threading.Tasks.Task<bool> DeleteDireccionAsync(ServicioGestion.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditDireccion", ReplyAction="http://tempuri.org/IServicioGestion/EditDireccionResponse")]
        bool EditDireccion(ServicioGestion.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditDireccion", ReplyAction="http://tempuri.org/IServicioGestion/EditDireccionResponse")]
        System.Threading.Tasks.Task<bool> EditDireccionAsync(ServicioGestion.DireccionData street, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetDireccion", ReplyAction="http://tempuri.org/IServicioGestion/GetDireccionResponse")]
        ServicioGestion.DireccionData[] GetDireccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetDireccion", ReplyAction="http://tempuri.org/IServicioGestion/GetDireccionResponse")]
        System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> GetDireccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetSector", ReplyAction="http://tempuri.org/IServicioGestion/GetSectorResponse")]
        ServicioGestion.SectorData[] GetSector();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetSector", ReplyAction="http://tempuri.org/IServicioGestion/GetSectorResponse")]
        System.Threading.Tasks.Task<ServicioGestion.SectorData[]> GetSectorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetEstadoAccionResponse")]
        ServicioGestion.EstadoAccion[] GetEstadoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetEstadoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EstadoAccion[]> GetEstadoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllEstadoAccionResponse")]
        ServicioGestion.EstadoAccion[] GetAllEstadoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllEstadoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllEstadoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestion.EstadoAccion[]> GetAllEstadoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetContactoResponse")]
        ServicioGestion.ContactoData[] GetContacto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.ContactoData[]> GetContactoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteContacto", ReplyAction="http://tempuri.org/IServicioGestion/DeleteContactoResponse")]
        bool DeleteContacto(ServicioGestion.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteContacto", ReplyAction="http://tempuri.org/IServicioGestion/DeleteContactoResponse")]
        System.Threading.Tasks.Task<bool> DeleteContactoAsync(ServicioGestion.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddContacto", ReplyAction="http://tempuri.org/IServicioGestion/AddContactoResponse")]
        bool AddContacto(ServicioGestion.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddContacto", ReplyAction="http://tempuri.org/IServicioGestion/AddContactoResponse")]
        System.Threading.Tasks.Task<bool> AddContactoAsync(ServicioGestion.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditContacto", ReplyAction="http://tempuri.org/IServicioGestion/EditContactoResponse")]
        bool EditContacto(ServicioGestion.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditContacto", ReplyAction="http://tempuri.org/IServicioGestion/EditContactoResponse")]
        System.Threading.Tasks.Task<bool> EditContactoAsync(ServicioGestion.ContactoData contacto, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesEmpresaResponse")]
        ServicioGestion.DireccionData[] getDirecionesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> getDirecionesEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesContacto", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesContactoResponse")]
        ServicioGestion.DireccionData[] getDirecionesContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getDirecionesContacto", ReplyAction="http://tempuri.org/IServicioGestion/getDirecionesContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> getDirecionesContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetNumeroTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetNumeroTelefonoResponse")]
        ServicioGestion.TelefonoData GetNumeroTelefono(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetNumeroTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetNumeroTelefonoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TelefonoData> GetNumeroTelefonoAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTelefonoResponse")]
        ServicioGestion.TelefonoData GetIdTelefono(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTelefono", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTelefonoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TelefonoData> GetIdTelefonoAsync(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTelefonos", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTelefonosResponse")]
        ServicioGestion.TelefonoData[] GetAllTelefonos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTelefonos", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTelefonosResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetAllTelefonosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddTelefono", ReplyAction="http://tempuri.org/IServicioGestion/AddTelefonoResponse")]
        int AddTelefono(ServicioGestion.TelefonoData t, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/AddTelefono", ReplyAction="http://tempuri.org/IServicioGestion/AddTelefonoResponse")]
        System.Threading.Tasks.Task<int> AddTelefonoAsync(ServicioGestion.TelefonoData t, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditTelefono", ReplyAction="http://tempuri.org/IServicioGestion/EditTelefonoResponse")]
        int EditTelefono(ServicioGestion.TelefonoData t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/EditTelefono", ReplyAction="http://tempuri.org/IServicioGestion/EditTelefonoResponse")]
        System.Threading.Tasks.Task<int> EditTelefonoAsync(ServicioGestion.TelefonoData t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteTelefono", ReplyAction="http://tempuri.org/IServicioGestion/DeleteTelefonoResponse")]
        bool DeleteTelefono(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/DeleteTelefono", ReplyAction="http://tempuri.org/IServicioGestion/DeleteTelefonoResponse")]
        System.Threading.Tasks.Task<bool> DeleteTelefonoAsync(int idTelefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTipoAccionResponse")]
        ServicioGestion.TipoDeAccionData GetIdTipoAccion(int idTipoAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetIdTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetIdTipoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TipoDeAccionData> GetIdTipoAccionAsync(int idTipoAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTipoAccionResponse")]
        ServicioGestion.TipoDeAccionData[] GetAllTipoAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetAllTipoAccion", ReplyAction="http://tempuri.org/IServicioGestion/GetAllTipoAccionResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TipoDeAccionData[]> GetAllTipoAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosEmpresaResponse")]
        ServicioGestion.TelefonoData[] GetTelefonosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetTelefonosEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContactosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetContactosEmpresaResponse")]
        ServicioGestion.ContactoData[] GetContactosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetContactosEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/GetContactosEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.ContactoData[]> GetContactosEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosContactoResponse")]
        ServicioGestion.TelefonoData[] GetTelefonosContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/GetTelefonosContacto", ReplyAction="http://tempuri.org/IServicioGestion/GetTelefonosContactoResponse")]
        System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetTelefonosContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addUsuario", ReplyAction="http://tempuri.org/IServicioGestion/addUsuarioResponse")]
        bool addUsuario(ServicioGestion.UsuarioData usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addUsuario", ReplyAction="http://tempuri.org/IServicioGestion/addUsuarioResponse")]
        System.Threading.Tasks.Task<bool> addUsuarioAsync(ServicioGestion.UsuarioData usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteUsuario", ReplyAction="http://tempuri.org/IServicioGestion/deleteUsuarioResponse")]
        bool deleteUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteUsuario", ReplyAction="http://tempuri.org/IServicioGestion/deleteUsuarioResponse")]
        System.Threading.Tasks.Task<bool> deleteUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editUsuario", ReplyAction="http://tempuri.org/IServicioGestion/editUsuarioResponse")]
        bool editUsuario(int idUsuario, ServicioGestion.UsuarioData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editUsuario", ReplyAction="http://tempuri.org/IServicioGestion/editUsuarioResponse")]
        System.Threading.Tasks.Task<bool> editUsuarioAsync(int idUsuario, ServicioGestion.UsuarioData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAllUsuariosResponse")]
        ServicioGestion.UsuarioData[] getAllUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAllUsuariosResponse")]
        System.Threading.Tasks.Task<ServicioGestion.UsuarioData[]> getAllUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getUsuario", ReplyAction="http://tempuri.org/IServicioGestion/getUsuarioResponse")]
        ServicioGestion.UsuarioData getUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getUsuario", ReplyAction="http://tempuri.org/IServicioGestion/getUsuarioResponse")]
        System.Threading.Tasks.Task<ServicioGestion.UsuarioData> getUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/addAccionComercialResponse")]
        bool addAccionComercial(ServicioGestion.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/addAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/addAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> addAccionComercialAsync(ServicioGestion.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/deleteAccionComercialResponse")]
        bool deleteAccionComercial(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/deleteAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/deleteAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> deleteAccionComercialAsync(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/editAccionComercialResponse")]
        bool editAccionComercial(int idAccion, ServicioGestion.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/editAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/editAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> editAccionComercialAsync(int idAccion, ServicioGestion.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllAccionesComerciales", ReplyAction="http://tempuri.org/IServicioGestion/getAllAccionesComercialesResponse")]
        ServicioGestion.AccionComercialMostrarData[] getAllAccionesComerciales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAllAccionesComerciales", ReplyAction="http://tempuri.org/IServicioGestion/getAllAccionesComercialesResponse")]
        System.Threading.Tasks.Task<ServicioGestion.AccionComercialMostrarData[]> getAllAccionesComercialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/getAccionComercialResponse")]
        ServicioGestion.AccionComercialData getAccionComercial(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionComercial", ReplyAction="http://tempuri.org/IServicioGestion/getAccionComercialResponse")]
        System.Threading.Tasks.Task<ServicioGestion.AccionComercialData> getAccionComercialAsync(int idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuariosResponse")]
        ServicioGestion.AccionComercialData[] getAccionesComercialesUsuarios(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuarios", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesUsuariosResponse")]
        System.Threading.Tasks.Task<ServicioGestion.AccionComercialData[]> getAccionesComercialesUsuariosAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresaResponse")]
        ServicioGestion.AccionComercialData[] getAccionesComercialesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/IServicioGestion/getAccionesComercialesEmpresaResponse")]
        System.Threading.Tasks.Task<ServicioGestion.AccionComercialData[]> getAccionesComercialesEmpresaAsync(int idEmpresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGestionChannel : ServicioGestionTestSpace.ServiceReference1.IServicioGestion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGestionClient : System.ServiceModel.ClientBase<ServicioGestionTestSpace.ServiceReference1.IServicioGestion>, ServicioGestionTestSpace.ServiceReference1.IServicioGestion {
        
        public ServicioGestionClient() {
        }
        
        public ServicioGestionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGestionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGestionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int addEmail(string correo, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.addEmail(correo, empData, conData);
        }
        
        public System.Threading.Tasks.Task<int> addEmailAsync(string correo, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.addEmailAsync(correo, empData, conData);
        }
        
        public ServicioGestion.EmailData[] getAllEmail() {
            return base.Channel.getAllEmail();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getAllEmailAsync() {
            return base.Channel.getAllEmailAsync();
        }
        
        public ServicioGestion.EmailData getEmailId(int id) {
            return base.Channel.getEmailId(id);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmailData> getEmailIdAsync(int id) {
            return base.Channel.getEmailIdAsync(id);
        }
        
        public ServicioGestion.EmailData getEmailCorreo(string correo) {
            return base.Channel.getEmailCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmailData> getEmailCorreoAsync(string correo) {
            return base.Channel.getEmailCorreoAsync(correo);
        }
        
        public bool deleteEmail(int idEmail) {
            return base.Channel.deleteEmail(idEmail);
        }
        
        public System.Threading.Tasks.Task<bool> deleteEmailAsync(int idEmail) {
            return base.Channel.deleteEmailAsync(idEmail);
        }
        
        public bool editEmail(int idEmail, string correo) {
            return base.Channel.editEmail(idEmail, correo);
        }
        
        public System.Threading.Tasks.Task<bool> editEmailAsync(int idEmail, string correo) {
            return base.Channel.editEmailAsync(idEmail, correo);
        }
        
        public bool addEmpresa(string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.addEmpresa(cif, nombreComercial, razon, web, sector);
        }
        
        public System.Threading.Tasks.Task<bool> addEmpresaAsync(string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.addEmpresaAsync(cif, nombreComercial, razon, web, sector);
        }
        
        public ServicioGestion.EmpresaData[] getAllEmpresa() {
            return base.Channel.getAllEmpresa();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmpresaData[]> getAllEmpresaAsync() {
            return base.Channel.getAllEmpresaAsync();
        }
        
        public ServicioGestion.EmpresaData getEmpresaCif(string cif) {
            return base.Channel.getEmpresaCif(cif);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmpresaData> getEmpresaCifAsync(string cif) {
            return base.Channel.getEmpresaCifAsync(cif);
        }
        
        public ServicioGestion.EmpresaData getEmpresaId(int id) {
            return base.Channel.getEmpresaId(id);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmpresaData> getEmpresaIdAsync(int id) {
            return base.Channel.getEmpresaIdAsync(id);
        }
        
        public ServicioGestion.EmpresaData[] getEmpresaSector(int idSector) {
            return base.Channel.getEmpresaSector(idSector);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmpresaData[]> getEmpresaSectorAsync(int idSector) {
            return base.Channel.getEmpresaSectorAsync(idSector);
        }
        
        public bool deleteEmpresa(int idEmpresa) {
            return base.Channel.deleteEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<bool> deleteEmpresaAsync(int idEmpresa) {
            return base.Channel.deleteEmpresaAsync(idEmpresa);
        }
        
        public bool editEmpresa(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.editEmpresa(idEmpresa, cif, nombreComercial, razon, web, sector);
        }
        
        public System.Threading.Tasks.Task<bool> editEmpresaAsync(int idEmpresa, string cif, string nombreComercial, string razon, string web, int sector) {
            return base.Channel.editEmpresaAsync(idEmpresa, cif, nombreComercial, razon, web, sector);
        }
        
        public ServicioGestion.EmailData[] getMailEmpresa(int idEmpresa) {
            return base.Channel.getMailEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getMailEmpresaAsync(int idEmpresa) {
            return base.Channel.getMailEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestion.EmailData[] getMailContacto(int idContacto) {
            return base.Channel.getMailContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EmailData[]> getMailContactoAsync(int idContacto) {
            return base.Channel.getMailContactoAsync(idContacto);
        }
        
        public bool AddDireccion(ServicioGestion.DireccionData street, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.AddDireccion(street, empData, conData);
        }
        
        public System.Threading.Tasks.Task<bool> AddDireccionAsync(ServicioGestion.DireccionData street, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.AddDireccionAsync(street, empData, conData);
        }
        
        public bool DeleteDireccion(ServicioGestion.DireccionData street, int id) {
            return base.Channel.DeleteDireccion(street, id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDireccionAsync(ServicioGestion.DireccionData street, int id) {
            return base.Channel.DeleteDireccionAsync(street, id);
        }
        
        public bool EditDireccion(ServicioGestion.DireccionData street, int id) {
            return base.Channel.EditDireccion(street, id);
        }
        
        public System.Threading.Tasks.Task<bool> EditDireccionAsync(ServicioGestion.DireccionData street, int id) {
            return base.Channel.EditDireccionAsync(street, id);
        }
        
        public ServicioGestion.DireccionData[] GetDireccion() {
            return base.Channel.GetDireccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> GetDireccionAsync() {
            return base.Channel.GetDireccionAsync();
        }
        
        public ServicioGestion.SectorData[] GetSector() {
            return base.Channel.GetSector();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.SectorData[]> GetSectorAsync() {
            return base.Channel.GetSectorAsync();
        }
        
        public ServicioGestion.EstadoAccion[] GetEstadoAccion() {
            return base.Channel.GetEstadoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EstadoAccion[]> GetEstadoAccionAsync() {
            return base.Channel.GetEstadoAccionAsync();
        }
        
        public ServicioGestion.EstadoAccion[] GetAllEstadoAccion() {
            return base.Channel.GetAllEstadoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.EstadoAccion[]> GetAllEstadoAccionAsync() {
            return base.Channel.GetAllEstadoAccionAsync();
        }
        
        public ServicioGestion.ContactoData[] GetContacto() {
            return base.Channel.GetContacto();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.ContactoData[]> GetContactoAsync() {
            return base.Channel.GetContactoAsync();
        }
        
        public bool DeleteContacto(ServicioGestion.ContactoData contacto, int id) {
            return base.Channel.DeleteContacto(contacto, id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteContactoAsync(ServicioGestion.ContactoData contacto, int id) {
            return base.Channel.DeleteContactoAsync(contacto, id);
        }
        
        public bool AddContacto(ServicioGestion.ContactoData contacto) {
            return base.Channel.AddContacto(contacto);
        }
        
        public System.Threading.Tasks.Task<bool> AddContactoAsync(ServicioGestion.ContactoData contacto) {
            return base.Channel.AddContactoAsync(contacto);
        }
        
        public bool EditContacto(ServicioGestion.ContactoData contacto, int id) {
            return base.Channel.EditContacto(contacto, id);
        }
        
        public System.Threading.Tasks.Task<bool> EditContactoAsync(ServicioGestion.ContactoData contacto, int id) {
            return base.Channel.EditContactoAsync(contacto, id);
        }
        
        public ServicioGestion.DireccionData[] getDirecionesEmpresa(int idEmpresa) {
            return base.Channel.getDirecionesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> getDirecionesEmpresaAsync(int idEmpresa) {
            return base.Channel.getDirecionesEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestion.DireccionData[] getDirecionesContacto(int idContacto) {
            return base.Channel.getDirecionesContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.DireccionData[]> getDirecionesContactoAsync(int idContacto) {
            return base.Channel.getDirecionesContactoAsync(idContacto);
        }
        
        public ServicioGestion.TelefonoData GetNumeroTelefono(string telefono) {
            return base.Channel.GetNumeroTelefono(telefono);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TelefonoData> GetNumeroTelefonoAsync(string telefono) {
            return base.Channel.GetNumeroTelefonoAsync(telefono);
        }
        
        public ServicioGestion.TelefonoData GetIdTelefono(int idTelefono) {
            return base.Channel.GetIdTelefono(idTelefono);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TelefonoData> GetIdTelefonoAsync(int idTelefono) {
            return base.Channel.GetIdTelefonoAsync(idTelefono);
        }
        
        public ServicioGestion.TelefonoData[] GetAllTelefonos() {
            return base.Channel.GetAllTelefonos();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetAllTelefonosAsync() {
            return base.Channel.GetAllTelefonosAsync();
        }
        
        public int AddTelefono(ServicioGestion.TelefonoData t, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.AddTelefono(t, empData, conData);
        }
        
        public System.Threading.Tasks.Task<int> AddTelefonoAsync(ServicioGestion.TelefonoData t, ServicioGestion.EmpresaData empData, ServicioGestion.ContactoData conData) {
            return base.Channel.AddTelefonoAsync(t, empData, conData);
        }
        
        public int EditTelefono(ServicioGestion.TelefonoData t) {
            return base.Channel.EditTelefono(t);
        }
        
        public System.Threading.Tasks.Task<int> EditTelefonoAsync(ServicioGestion.TelefonoData t) {
            return base.Channel.EditTelefonoAsync(t);
        }
        
        public bool DeleteTelefono(int idTelefono) {
            return base.Channel.DeleteTelefono(idTelefono);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTelefonoAsync(int idTelefono) {
            return base.Channel.DeleteTelefonoAsync(idTelefono);
        }
        
        public ServicioGestion.TipoDeAccionData GetIdTipoAccion(int idTipoAccion) {
            return base.Channel.GetIdTipoAccion(idTipoAccion);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TipoDeAccionData> GetIdTipoAccionAsync(int idTipoAccion) {
            return base.Channel.GetIdTipoAccionAsync(idTipoAccion);
        }
        
        public ServicioGestion.TipoDeAccionData[] GetAllTipoAccion() {
            return base.Channel.GetAllTipoAccion();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TipoDeAccionData[]> GetAllTipoAccionAsync() {
            return base.Channel.GetAllTipoAccionAsync();
        }
        
        public ServicioGestion.TelefonoData[] GetTelefonosEmpresa(int idEmpresa) {
            return base.Channel.GetTelefonosEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetTelefonosEmpresaAsync(int idEmpresa) {
            return base.Channel.GetTelefonosEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestion.ContactoData[] GetContactosEmpresa(int idEmpresa) {
            return base.Channel.GetContactosEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.ContactoData[]> GetContactosEmpresaAsync(int idEmpresa) {
            return base.Channel.GetContactosEmpresaAsync(idEmpresa);
        }
        
        public ServicioGestion.TelefonoData[] GetTelefonosContacto(int idContacto) {
            return base.Channel.GetTelefonosContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.TelefonoData[]> GetTelefonosContactoAsync(int idContacto) {
            return base.Channel.GetTelefonosContactoAsync(idContacto);
        }
        
        public bool addUsuario(ServicioGestion.UsuarioData usuario) {
            return base.Channel.addUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> addUsuarioAsync(ServicioGestion.UsuarioData usuario) {
            return base.Channel.addUsuarioAsync(usuario);
        }
        
        public bool deleteUsuario(int idUsuario) {
            return base.Channel.deleteUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> deleteUsuarioAsync(int idUsuario) {
            return base.Channel.deleteUsuarioAsync(idUsuario);
        }
        
        public bool editUsuario(int idUsuario, ServicioGestion.UsuarioData user) {
            return base.Channel.editUsuario(idUsuario, user);
        }
        
        public System.Threading.Tasks.Task<bool> editUsuarioAsync(int idUsuario, ServicioGestion.UsuarioData user) {
            return base.Channel.editUsuarioAsync(idUsuario, user);
        }
        
        public ServicioGestion.UsuarioData[] getAllUsuarios() {
            return base.Channel.getAllUsuarios();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.UsuarioData[]> getAllUsuariosAsync() {
            return base.Channel.getAllUsuariosAsync();
        }
        
        public ServicioGestion.UsuarioData getUsuario(int idUsuario) {
            return base.Channel.getUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.UsuarioData> getUsuarioAsync(int idUsuario) {
            return base.Channel.getUsuarioAsync(idUsuario);
        }
        
        public bool addAccionComercial(ServicioGestion.AccionComercialData accion) {
            return base.Channel.addAccionComercial(accion);
        }
        
        public System.Threading.Tasks.Task<bool> addAccionComercialAsync(ServicioGestion.AccionComercialData accion) {
            return base.Channel.addAccionComercialAsync(accion);
        }
        
        public bool deleteAccionComercial(int idAccion) {
            return base.Channel.deleteAccionComercial(idAccion);
        }
        
        public System.Threading.Tasks.Task<bool> deleteAccionComercialAsync(int idAccion) {
            return base.Channel.deleteAccionComercialAsync(idAccion);
        }
        
        public bool editAccionComercial(int idAccion, ServicioGestion.AccionComercialData accion) {
            return base.Channel.editAccionComercial(idAccion, accion);
        }
        
        public System.Threading.Tasks.Task<bool> editAccionComercialAsync(int idAccion, ServicioGestion.AccionComercialData accion) {
            return base.Channel.editAccionComercialAsync(idAccion, accion);
        }
        
        public ServicioGestion.AccionComercialMostrarData[] getAllAccionesComerciales() {
            return base.Channel.getAllAccionesComerciales();
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.AccionComercialMostrarData[]> getAllAccionesComercialesAsync() {
            return base.Channel.getAllAccionesComercialesAsync();
        }
        
        public ServicioGestion.AccionComercialData getAccionComercial(int idAccion) {
            return base.Channel.getAccionComercial(idAccion);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.AccionComercialData> getAccionComercialAsync(int idAccion) {
            return base.Channel.getAccionComercialAsync(idAccion);
        }
        
        public ServicioGestion.AccionComercialData[] getAccionesComercialesUsuarios(int idUsuario) {
            return base.Channel.getAccionesComercialesUsuarios(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.AccionComercialData[]> getAccionesComercialesUsuariosAsync(int idUsuario) {
            return base.Channel.getAccionesComercialesUsuariosAsync(idUsuario);
        }
        
        public ServicioGestion.AccionComercialData[] getAccionesComercialesEmpresa(int idEmpresa) {
            return base.Channel.getAccionesComercialesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<ServicioGestion.AccionComercialData[]> getAccionesComercialesEmpresaAsync(int idEmpresa) {
            return base.Channel.getAccionesComercialesEmpresaAsync(idEmpresa);
        }
    }
}
